export enum Exchange {
    NYSE = 1, // New York Stock Exchange
    NASDAQ = 2, // National Association of Securities Dealers Automated Quotations
    TASE = 3, // Tel Aviv Stock Exchange
    LSE = 4, // London Stock Exchange
    TSX = 5, // Toronto Stock Exchange
    SSE = 6, // Shanghai Stock Exchange
    HKEX = 7, // Hong Kong Exchange
    ASX = 8, // Australian Securities Exchange
    BSE = 9, // Bombay Stock Exchange
    Bovespa = 10, // Bolsa de Valores do Estado de São Paulo
    BMFBOVESPA = 11, // Bolsa de Mercadorias e Futuros de São Paulo
    B3 = 12,
    BME = 13,
    Euronext = 14,
    EuronextParis = 15,
    EuronextAmsterdam = 16,
    EuronextBrussels = 17,
    EuronextLisbon = 18,
    EuronextMadrid = 19,
    EuronextRome = 20,
    EuronextStockholm = 21,
    EuronextZurich = 22,
    EuronextAthens = 23,
    EuronextBucharest = 24,
    EuronextBudapest = 25,
    EuronextCopenhagen = 26,
    EuronextDublin = 27,
    EuronextEdinburgh = 28
}
